#!/bin/bash

# create necessary directories, if not yet existend
declare -a directories=(
  ".config"
  ".config/bspwn"
  ".config/sxhkd"
  ".config/polybar"
  ".config/dunst/"
  ".background"
  "refind"
)

for dir in "${directories[@]}"
do
  if [[ ! -d "$dir" ]]
  then
    mkdir -p "$dir"
  fi
done    

# copy all relevant files to current folder

# scripts
cp -r ~/bin ./

# configs
cp ~/.config/bspwm/* ./.config/bspwm
cp ~/.config/sxhkd/* ./.config/sxhkd
cp ~/.config/polybar/* ./.config/polybar
cp ~/.config/dunst/* ./.config/dunst

# backgrounds
cp ~/.background/background.png ./.background/

# rEFInd
cp /boot/efi/EFI/refind/custom* ./refind
cp -r /boot/efi/EFI/refind/themes ./refind

# xinit
cp ~/.xinitrc ./

# X resources
cp ~/.Xresources ./

# zsh
cp ~/.zprofile ./
cp ~/.zshenv ./
cp ~/.zshrc ./

# create commit with given message, or a default
git add .
if [[ "$1" != "" ]]
then
    git commit -m "$@"
else
    git commit -m "Updated dotfiles"
fi

# push to git
git push

# clean up files
rm `find . -type f ! -ipath '*.git*' ! -iname '*.md' ! -name 'exportToGit' ! -name 'importFromGit' ! -name '.'`
rmdir `find . -type d -empty`
