#!/bin/bash

/bin/wine /home/niklas/.wine/drive_c/Program\ Files\ \(x86\)/Steam/steamapps/common/Dead\ Cells/deadcells.exe
#primusrun /bin/wine /home/niklas/.wine/drive_c/Program\ Files\ \(x86\)/Steam/steamapps/common/Dead\ Cells/deadcells.exe
