#!/bin/sh

## Figure out current screen size
#SCREENWIDTH=$(xrandr -q | grep Screen | awk '{print $8}')
#SCREENHEIGHT=$(xrandr -q | grep Screen | awk '{print $10}' | sed s/,//)
#
## How close to the screen edges do we begin/end?
#EDGEWIDTH=10
#DMENUWIDTH=$(($SCREENWIDTH - $(($EDGEWIDTH + $EDGEWIDTH))))
#
## dmenu X/Y coordinates
#XPOS=$EDGEWIDTH
#YPOS=$(($(($SCREENHEIGHT / 2)) - 250))

# Currently hardcoded, because only in use on one machine and therefore not needed (faster)
DMENUWIDTH=1900
XPOS=10
YPOS=290

FGSELECT="#000"
#FGSELECT="#A3A6AB"
BGSELECT="#8C9440"
FG="#ebdbb2"
BG="#282828"
export dmenu_font="-*-terminus-*-*-*-*-*-*-*-*-*-*-*-*"

dmenu_run -i -w $DMENUWIDTH -x $XPOS -y $YPOS -fn $dmenu_font -nb $BG -nf $FG -sb $BGSELECT -sf $FGSELECT -p "run:" -dim 0.75

#echo "-i -w $DMENUWIDTH -x $XPOS -y $YPOS -fn $FONT -nb $BG -nf $FG -sb $BGSELECT -sf $FGSELECT" >> test2
#echo $dmenu_args >> test2
#dmenu_run ${dmenu_args} -p "run:" -dim 0.75
