#! /bin/bash

sxhkd &

# bspwn settings
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer false
bspc config click_to_focus       true

bspc config normal_border_color "#3c3836"
bspc config focused_border_color "#665c54"
bspc config presel_feedback_color "#7c6f64"

bspc rule -a Chromium desktop=^2
